In [149]:
import pandas as pd
import numpy as np

df = pd.read_csv("SBCscreen.csv")

In [150]:
df

,Ticker,Short Name,SBC,Market Cap,ValTraded,Market Cap.1,PriceD-1,P/E
0,AMZN US Equity,AMAZON.COM INC,19.62B,1.05T,11.27B,1.05T,102.18,138.36
1,GOOGL US Equity,ALPHABET INC-A,19.36B,1.32T,4.81B,1.32T,102.90,21.24
2,META US Equity,META PLATFORMS-A,11.99B,482.39B,12.84B,482.39B,186.06,16.92
3,AAPL US Equity,APPLE INC,9.04B,2.40T,14.55B,2.40T,151.73,25.76
4,MSFT US Equity,MICROSOFT CORP,7.50B,1.91T,7.63B,1.91T,256.77,28.03
...,...,...,...,...,...,...,...,...
2995,MUV2 GR Equity,MUENCHENER RUE-R,--,48.69B,129.39M,48.69B,347.85,16.44
2996,VO US Equity,VANGUARD MID-C E,--,48.41B,149.42M,48.41B,221.31,--
2997,8001 JP Equity,ITOCHU CORP,--,48.29B,102.72M,48.29B,30.70,7.24
2998,000963 CH Equity,HUADONG MEDICI-A,--,12.12B,53.80M,12.12B,6.89,34.28
2999,IWN US Equity,ISHARES RUSSELL,--,12.13B,213.16M,12.13B,154.18,--

In [151]:
df = pd.read_csv("SBCscreen.csv")
import pandas as pd

def convert_column(df, col_name):
    df[col_name] = df[col_name].apply(lambda x: convert_to_float(x))
    print("done with:", col_name)

def convert_to_float(x):
    if type(x) == str:
        if x[-1] == 'M':
            return float(x[:-1]) * 1e6
        elif x[-1] == 'B':
            return float(x[:-1]) * 1e9
        elif x[-1] == 'T':
            return float(x[:-1]) * 1e12
        elif x[-1] == 'k':
            return float(x[:-1]) * 1e3
    try:
        return float(x)
    except ValueError:
        return float('nan')


cols_to_convert = ['SBC', 'Market Cap', 'ValTraded', 'Market Cap.1', 'PriceD-1']
for col in cols_to_convert:
    convert_column(df, col)
# df.to_csv("converted_file.csv", index=False, float_format="%.2f")

df = df[df['SBC'].notnull()]
df

done with: SBC
done with: Market Cap
done with: ValTraded
done with: Market Cap.1
done with: PriceD-1

,Ticker,Short Name,SBC,Market Cap,ValTraded,Market Cap.1,PriceD-1,P/E
0,AMZN US Equity,AMAZON.COM INC,1.962000e+10,1.050000e+12,1.127000e+10,1.050000e+12,102.18,138.36
1,GOOGL US Equity,ALPHABET INC-A,1.936000e+10,1.320000e+12,4.810000e+09,1.320000e+12,102.90,21.24
2,META US Equity,META PLATFORMS-A,1.199000e+10,4.823900e+11,1.284000e+10,4.823900e+11,186.06,16.92
3,AAPL US Equity,APPLE INC,9.040000e+09,2.400000e+12,1.455000e+10,2.400000e+12,151.73,25.76
4,MSFT US Equity,MICROSOFT CORP,7.500000e+09,1.910000e+12,7.630000e+09,1.910000e+12,256.77,28.03
...,...,...,...,...,...,...,...,...
1268,GENS SP Equity,GENTING SINGAPOR,-4.110000e+06,9.100000e+09,2.115000e+07,9.100000e+09,0.75,67.18
1269,BKG LN Equity,BERKELEY GROUP,-1.169000e+07,5.550000e+09,1.298000e+07,5.550000e+09,51.24,10.25
1270,KESKOB FH Equity,KESKO OYJ-B,-1.254000e+07,8.650000e+09,2.272000e+07,8.650000e+09,21.62,12.9
1271,SBIN IN Equity,STATE BANK IND,-1.110100e+08,5.884000e+10,2.147900e+08,5.884000e+10,6.61,10.37
1272,TPG US Equity,TPG INC,-4.000000e+09,1.021000e+10,9.570000e+06,1.021000e+10,33.06,--

In [152]:
df['SBC/MktCap'] = df['SBC'] / df['Market Cap']
df

,Ticker,Short Name,SBC,Market Cap,ValTraded,Market Cap.1,PriceD-1,P/E,SBC/MktCap
0,AMZN US Equity,AMAZON.COM INC,1.962000e+10,1.050000e+12,1.127000e+10,1.050000e+12,102.18,138.36,0.018686
1,GOOGL US Equity,ALPHABET INC-A,1.936000e+10,1.320000e+12,4.810000e+09,1.320000e+12,102.90,21.24,0.014667
2,META US Equity,META PLATFORMS-A,1.199000e+10,4.823900e+11,1.284000e+10,4.823900e+11,186.06,16.92,0.024855
3,AAPL US Equity,APPLE INC,9.040000e+09,2.400000e+12,1.455000e+10,2.400000e+12,151.73,25.76,0.003767
4,MSFT US Equity,MICROSOFT CORP,7.500000e+09,1.910000e+12,7.630000e+09,1.910000e+12,256.77,28.03,0.003927
...,...,...,...,...,...,...,...,...,...
1268,GENS SP Equity,GENTING SINGAPOR,-4.110000e+06,9.100000e+09,2.115000e+07,9.100000e+09,0.75,67.18,-0.000452
1269,BKG LN Equity,BERKELEY GROUP,-1.169000e+07,5.550000e+09,1.298000e+07,5.550000e+09,51.24,10.25,-0.002106
1270,KESKOB FH Equity,KESKO OYJ-B,-1.254000e+07,8.650000e+09,2.272000e+07,8.650000e+09,21.62,12.9,-0.001450
1271,SBIN IN Equity,STATE BANK IND,-1.110100e+08,5.884000e+10,2.147900e+08,5.884000e+10,6.61,10.37,-0.001887
1272,TPG US Equity,TPG INC,-4.000000e+09,1.021000e+10,9.570000e+06,1.021000e+10,33.06,--,-0.391773

In [153]:
df.drop('PriceD-1', axis=1, inplace=True)
df.drop('ValTraded', axis=1, inplace=True)
df.drop('Market Cap.1', axis=1, inplace=True)
df

,Ticker,Short Name,SBC,Market Cap,P/E,SBC/MktCap
0,AMZN US Equity,AMAZON.COM INC,1.962000e+10,1.050000e+12,138.36,0.018686
1,GOOGL US Equity,ALPHABET INC-A,1.936000e+10,1.320000e+12,21.24,0.014667
2,META US Equity,META PLATFORMS-A,1.199000e+10,4.823900e+11,16.92,0.024855
3,AAPL US Equity,APPLE INC,9.040000e+09,2.400000e+12,25.76,0.003767
4,MSFT US Equity,MICROSOFT CORP,7.500000e+09,1.910000e+12,28.03,0.003927
...,...,...,...,...,...,...
1268,GENS SP Equity,GENTING SINGAPOR,-4.110000e+06,9.100000e+09,67.18,-0.000452
1269,BKG LN Equity,BERKELEY GROUP,-1.169000e+07,5.550000e+09,10.25,-0.002106
1270,KESKOB FH Equity,KESKO OYJ-B,-1.254000e+07,8.650000e+09,12.9,-0.001450
1271,SBIN IN Equity,STATE BANK IND,-1.110100e+08,5.884000e+10,10.37,-0.001887
1272,TPG US Equity,TPG INC,-4.000000e+09,1.021000e+10,--,-0.391773

In [154]:
df['Market Cap']=df['Market Cap'].apply(lambda x: "{:,.0f}".format(x))
df['SBC']=df['SBC'].apply(lambda x: "{:,.0f}".format(x))
df['SBC/MktCap']=df['SBC/MktCap'].apply(lambda x: "{:.1%}".format(x))
df

,Ticker,Short Name,SBC,Market Cap,P/E,SBC/MktCap
0,AMZN US Equity,AMAZON.COM INC,"19,620,000,000","1,050,000,000,000",138.36,1.9%
1,GOOGL US Equity,ALPHABET INC-A,"19,360,000,000","1,320,000,000,000",21.24,1.5%
2,META US Equity,META PLATFORMS-A,"11,990,000,000","482,390,000,000",16.92,2.5%
3,AAPL US Equity,APPLE INC,"9,040,000,000","2,400,000,000,000",25.76,0.4%
4,MSFT US Equity,MICROSOFT CORP,"7,500,000,000","1,910,000,000,000",28.03,0.4%
...,...,...,...,...,...,...
1268,GENS SP Equity,GENTING SINGAPOR,"-4,110,000","9,100,000,000",67.18,-0.0%
1269,BKG LN Equity,BERKELEY GROUP,"-11,690,000","5,550,000,000",10.25,-0.2%
1270,KESKOB FH Equity,KESKO OYJ-B,"-12,540,000","8,650,000,000",12.9,-0.1%
1271,SBIN IN Equity,STATE BANK IND,"-111,010,000","58,840,000,000",10.37,-0.2%
1272,TPG US Equity,TPG INC,"-4,000,000,000","10,210,000,000",--,-39.2%

In [155]:
df.sort_values("SBC/MktCap", ascending=False, inplace=True)
df

,Ticker,Short Name,SBC,Market Cap,P/E,SBC/MktCap
76,ROIV US Equity,ROIVANT SCIENCES,"564,960,000","5,760,000,000",--,9.8%
61,DKNG US Equity,DRAFTKINGS INC,"683,290,000","7,610,000,000",--,9.0%
27,SNAP US Equity,SNAP INC - A,"1,390,000,000","19,090,000,000",--,7.3%
43,CSGN SW Equity,CREDIT SUISS-REG,"1,010,000,000","13,830,000,000",--,7.3%
77,YMM US Equity,FULL TRUCK A-ADR,"562,630,000","8,040,000,000",--,7.0%
...,...,...,...,...,...,...
1265,CHP-U CN Equity,CHOICE PROPERTIE,"-2,040,000","7,880,000,000",7.78,-0.0%
1266,ITUB4 BZ Equity,ITAU UNIBAN-PREF,"-3,710,000","44,380,000,000",8.55,-0.0%
1267,EIM IN Equity,EICHER MOTORS,"-3,940,000","10,780,000,000",53.39,-0.0%
1268,GENS SP Equity,GENTING SINGAPOR,"-4,110,000","9,100,000,000",67.18,-0.0%
1259,SOL AU Equity,WASHINGTON H. SO,"-208,350","7,170,000,000",2.86k,-0.0%

In [156]:
df.to_csv("sortedfile.csv")